print("Buenos días")
print("El celular tiene un costo de $2000000")
c=int("2000000")
print("......................................")
print("")
print("Pero hoy contamos con un desuento del 15%")
print("......................................")
print("")
e=float(0.15)
et=float(c*e)
print(F"Tu descuento sertia de {et}")
print("......................................")
print("")
t=float(c-et)
print(F"El valor total aplicando el descuento seria: {t}")