print("Hola")
print("Agrega un numero")
a = float(input())
print("Agrega otro numero")
b = float(input())

print("Suma")
print("____")
print(F"a+b={a+b}")
print("____")
print("")

print("Resta")
print("____")
print(F"a-b={a-b}")
print("____")
print("")

print("Multiplicacion")
print("____")
print(F"a*b={a*b}")
print("____")
print("")

print("Division")
print("____")
print(F"El residuo de la division es={a%b}")
print("____")
print("")